import {useEffect,useState} from 'react';
import {request} from '../api';
import {Button} from './ui/button';
import {Collapsible,CollapsibleContent,CollapsibleTrigger} from './ui/collapsible';
import {FormInput} from './controls';
import {ErrorLine,Field,Notice} from './ui';
interface Deployment {dataDir:string;webDir:string;compatibilityPort:number}
interface View {active:Deployment;next:Deployment;restartRequired:boolean;file:string;database:string;configFile:string}
interface Service {values:Record<string,string>;sources:Record<string,string>;file:string}
const serviceLabels:Record<string,string>={label:'Proxy service label',brewLabel:'Homebrew service label',brewBinary:'Homebrew executable',brewPrefix:'Homebrew prefix',config:'Proxy configuration file',repository:'Release repository',consoleUrl:'Proxy URL for service checks'};
export function DeploymentSettings(){
 const [view,setView]=useState<View|null>(null),[draft,setDraft]=useState<Deployment|null>(null),[service,setService]=useState<Service|null>(null),[values,setValues]=useState<Record<string,string>>({});
 const [busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null),[saved,setSaved]=useState('');
 useEffect(()=>{Promise.all([request<View>('/api/deployment'),request<Service>('/api/service-settings')]).then(([d,s])=>{setView(d);setDraft(d.next);setService(s);setValues(s.values);},setError);},[]);
 async function saveDeployment(value:Deployment){setBusy(true);setError(null);try{const result=await request<View>('/api/deployment',{method:'PUT',body:JSON.stringify({dataDir:value.dataDir,webDir:value.webDir,compatibilityPort:value.compatibilityPort})});setView(result);setDraft(result.next);setSaved(result.restartRequired?'Saved. Restart CLIProxyAPI to apply deployment changes.':'Pending changes cleared.');}catch(e){setError(e);}finally{setBusy(false);}}
 async function saveService(){setBusy(true);setError(null);try{const patch=Object.fromEntries(Object.entries(values).filter(([k,v])=>service?.values[k]!==v));const result=await request<Service>('/api/service-settings',{method:'PUT',body:JSON.stringify(patch)});setService(result);setValues(result.values);setSaved('Saved in CLIProxyAPI. Service changes apply on the next installation or update.');}catch(e){setError(e);}finally{setBusy(false);}}
 return <Collapsible className="settings-section"><CollapsibleTrigger asChild><Button variant="secondary">Proxy storage and deployment</Button></CollapsibleTrigger><CollapsibleContent className="settings-fields"><p className="microcopy">CLIProxyAPI serves this frontend and owns its storage. There is no separate console backend.</p><ErrorLine error={error}/>{saved&&<p role="status">{saved}</p>}{view&&draft&&<><Field label="Proxy administration data directory" hint="A new directory is copied on proxy restart. Existing data stays available as a backup."><FormInput value={draft.dataDir} onChange={e=>setDraft({...draft,dataDir:e.target.value})}/></Field><Field label="Frontend build directory" hint="The web/dist folder containing index.html."><FormInput value={draft.webDir} onChange={e=>setDraft({...draft,webDir:e.target.value})}/></Field><Field label="Compatibility port" hint="Optional localhost listener owned by CLIProxyAPI for old connections. Use 0 to disable."><FormInput type="number" min={0} max={65535} value={draft.compatibilityPort} onChange={e=>setDraft({...draft,compatibilityPort:Number(e.target.value)})}/></Field><Button disabled={busy||JSON.stringify(draft)===JSON.stringify(view.next)} onClick={()=>void saveDeployment(draft)}>Save deployment changes</Button>{view.restartRequired&&<Notice tone="warn" title="Proxy restart required"><Button variant="ghost" disabled={busy} onClick={()=>void saveDeployment(view.active)}>Cancel pending changes</Button></Notice>}<p className="microcopy break-path">Proxy configuration: {view.configFile}<br/>Database: {view.database}</p></>}{service&&<><h3>Proxy service helper</h3>{Object.entries(serviceLabels).map(([k,label])=><Field label={label} key={k}><FormInput disabled={busy||service.sources[k]==='env'} value={values[k]||''} onChange={e=>setValues({...values,[k]:e.target.value})}/></Field>)}<Button disabled={busy||JSON.stringify(values)===JSON.stringify(service.values)} onClick={()=>void saveService()}>Save service settings</Button></>}</CollapsibleContent></Collapsible>;
}
